<<<<<<< HEAD
export class dataservices{
    static films =[
        
    { id:1,
        titre: 'Stranger Things', 
        Overview: 'overview', 
        ReleasedDate :'',
        Favorites:true,
        Rating:5,
        Runtime:0,
        nbview:0,
        ImgCaroussel:'.\..\imgfilms\ImgCarou\StrangerThings.jpg',
        ImgAff :'',
        Imgband:'',
        urlvideo:'',
        Cast:[],
        Genres :['série','horreur'],
        },
    { id:2,
        titre: 'Inception', 
        Overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person idea into a targets subconscious.', 
        ReleasedDate :'15-37-2010',
        Favorites:true,
        Rating:8.3,
        Runtime:148,
        nbview:0,
        ImgCaroussel:'',
        ImgAff :'http://image.tmdb.org/t/p/w500///s3TBrRGB1iav7gFOCNx3H31MoES.jpg">',
        Imgband:'http://image.tmdb.org/t/p/w500///s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
        urlvideo:'',
        Cast:[5,6,7,8],
        Genres :['film'],
        },
    { id:3,
        titre: 'Blade Runner', 
        Overview: 'In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.', 
        ReleasedDate :'25-06-1982',
        Favorites:true,
        Rating:7.9,
        Runtime:118,
        nbview:0,
        ImgCaroussel:'.\..\imgfilms\ImgCarou\BladeRunner.jpg',
        ImgAff :'http://image.tmdb.org/t/p/w500///vfzE3pjE5G7G7kcZWrA3fnbZo7V.jpg',
        Imgband:'http://image.tmdb.org/t/p/w500///eIi3klFf7mp3oL5EEF4mLIDs26r.jpg',
        urlvideo:'',
        Cast:[1,2,3,4],
        Genres :['film'],
        },
    { id:4,
        titre: 'Scoob', 
        Overview: 'In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.', 
        ReleasedDate :'15-05-2020',
        Favorites:false,
        Rating:8,
        Runtime:94,
        nbview:0,
        ImgCaroussel:'',
        ImgAff :'http://image.tmdb.org/t/p/w500///jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg',
        Imgband:'http://image.tmdb.org/t/p/w500///fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg',
        urlvideo:'',
        Cast:[9,10,11,12],
        Genres :['film'],
        },
    { id:5,
        titre: 'The Hunt', 
        Overview: "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers", 
        ReleasedDate :'11-03-2020',
        Favorites:false,
        Rating:6.7,
        Runtime:90,
        nbview:0,
        ImgCaroussel:'',
        ImgAff :'http://image.tmdb.org/t/p/w500///wxPhn4ef1EAo5njxwBkAEVrlJJG.jpg',
        Imgband:'http://image.tmdb.org/t/p/w500///naXUDz0VGK7aaPlEpsuYW8kNVsr.jpg',
        urlvideo:'',
        Cast:[2,3,4,5],
        Genres :['film'],
        },
    { id:6,
        titre: 'Babyteeth', 
        Overview: "A terminally ill teen upsets her parents when she falls in love with a small-time drug dealer.", 
        ReleasedDate :'18-06-2020',
        Favorites:true,
        Rating:5.2,
        Runtime:118,
        nbview:0,
        ImgCaroussel:'',
        ImgAff :'http://image.tmdb.org/t/p/w500///aINpljdt3VVMrCLtJW4BektwYOp.jpg',
        Imgband:'http://image.tmdb.org/t/p/w500///cjAirCV9TyTQcp7mFNRnvgkoVFV.jpg',
        urlvideo:'',
        Cast:[9,10,11,12],
        Genres :['film'],
        },
    { id:7,
        titre: 'Wasp Network', 
        Overview:"Havana, Cuba, 1990. René González, an airplane pilot, unexpectedly flees the country, leaving behind his wife Olga and his daughter Irma, and begins a new life in Miami, where he becomes a member of an anti-Castro organization.", 
        ReleasedDate :'29-01-2020',
        Favorites:true,
        Rating:6.4,
        Runtime:128,
        nbview:0,
        ImgCaroussel:'',
        ImgAff :'http://image.tmdb.org/t/p/w500///fOvqEunubL3wPskvtk2Ficfl0pH.jpg',
        Imgband:'http://image.tmdb.org/t/p/w500///72r4uAQGsa8KEv0DB2TpSu31lEB.jpg',
        urlvideo:'',
        Cast:[3,4,5,6],
        Genres :['série'],
        },
    { id:8,
        titre: 'Hamilton', 
        Overview:"Presenting the tale of American founding father Alexander Hamilton, this filmed version of the original Broadway smash hit is the story of America then, told by America now.", 
        ReleasedDate :'03-07-2020',
        Favorites:false,
        Rating:8.7,
        Runtime:160,
        nbview:0,
        ImgCaroussel:'',
        ImgAff :'http://image.tmdb.org/t/p/w500///h1B7tW0t399VDjAcWJh8m87469b.jpg',
        Imgband:'http://image.tmdb.org/t/p/w500///uWVkEo9PWHu9algZsiLPi6sRU64.jpg',
        urlvideo:'',
        Cast:[7,8,9,10],
        Genres :['film'],
        },
    { id:9,
        titre: 'Red Shoes and the Seven Dwarfs', 
        Overview:"Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.", 
        ReleasedDate :'25-07-2019',
        Favorites:false,
        Rating:6.7,
        Runtime:92,
        nbview:0,
        ImgCaroussel:'',
        ImgAff :'http://image.tmdb.org/t/p/w500///MBiKqTsouYqAACLYNDadsjhhC0.jpg',
        Imgband:'http://image.tmdb.org/t/p/w500///bga3i5jcejBekr2FCGJga1fYCh.jpg',
        urlvideo:'',
        Cast:[1,8,5,10],
        Genres :['Dessin Animé'],
=======
export class dataservices {
    static films = [

        {
            id: 1,
            titre: 'Stranger Things',
            Overview: 'overview',
            ReleasedDate: '',
            Favorites: true,
            Rating: 5,
            Runtime: 0,
            nbview: 0,
            ImgCaroussel: '.\..\imgfilms\ImgCarou\StrangerThings.jpg',
            ImgAff: '',
            Imgband: '',
            urlvideo: '',
            Cast: [],
            Genres: ['série', 'horreur'],
        },
        {
            id: 2,
            titre: 'Inception',
            Overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person"s idea into a targets subconscious.',
            ReleasedDate: '15-37-2010',
            Favorites: true,
            Rating: 8.3,
            Runtime: 148,
            nbview: 0,
            ImgCaroussel: '',
            ImgAff: 'http://image.tmdb.org/t/p/w500///s3TBrRGB1iav7gFOCNx3H31MoES.jpg">',
            Imgband: 'http://image.tmdb.org/t/p/w500///s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
            urlvideo: '',
            Cast: [5, 6, 7, 8],
            Genres: ['film'],
        },
        {
            id: 3,
            titre: 'Blade Runner',
            Overview: 'In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.',
            ReleasedDate: '25-06-1982',
            Favorites: true,
            Rating: 7.9,
            Runtime: 118,
            nbview: 0,
            ImgCaroussel: '.\..\imgfilms\ImgCarou\BladeRunner.jpg',
            ImgAff: 'http://image.tmdb.org/t/p/w500///vfzE3pjE5G7G7kcZWrA3fnbZo7V.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///eIi3klFf7mp3oL5EEF4mLIDs26r.jpg',
            urlvideo: '',
            Cast: [1, 2, 3, 4],
            Genres: ['film'],
        },
        {
            id: 4,
            titre: 'Scoob',
            Overview: 'In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.',
            ReleasedDate: '15-05-2020',
            Favorites: false,
            Rating: 8,
            Runtime: 94,
            nbview: 0,
            ImgCaroussel: '',
            ImgAff: 'http://image.tmdb.org/t/p/w500///jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg',
            urlvideo: '',
            Cast: [9, 10, 11, 12],
            Genres: ['film'],
        },
        {
            id: 5,
            titre: 'The Hunt',
            Overview: "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers",
            ReleasedDate: '11-03-2020',
            Favorites: false,
            Rating: 6.7,
            Runtime: 90,
            nbview: 0,
            ImgCaroussel: '',
            ImgAff: 'http://image.tmdb.org/t/p/w500///wxPhn4ef1EAo5njxwBkAEVrlJJG.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///naXUDz0VGK7aaPlEpsuYW8kNVsr.jpg',
            urlvideo: '',
            Cast: [2, 3, 4, 5],
            Genres: ['film'],
        },
        {
            id: 6,
            titre: 'Babyteeth',
            Overview: "A terminally ill teen upsets her parents when she falls in love with a small-time drug dealer.",
            ReleasedDate: '18-06-2020',
            Favorites: true,
            Rating: 5.2,
            Runtime: 118,
            nbview: 0,
            ImgCaroussel: '',
            ImgAff: 'http://image.tmdb.org/t/p/w500///aINpljdt3VVMrCLtJW4BektwYOp.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///cjAirCV9TyTQcp7mFNRnvgkoVFV.jpg',
            urlvideo: '',
            Cast: [9, 10, 11, 12],
            Genres: ['film'],
        },
        {
            id: 7,
            titre: 'Wasp Network',
            Overview: "Havana, Cuba, 1990. René González, an airplane pilot, unexpectedly flees the country, leaving behind his wife Olga and his daughter Irma, and begins a new life in Miami, where he becomes a member of an anti-Castro organization.",
            ReleasedDate: '29-01-2020',
            Favorites: true,
            Rating: 6.4,
            Runtime: 128,
            nbview: 0,
            ImgCaroussel: '',
            ImgAff: 'http://image.tmdb.org/t/p/w500///fOvqEunubL3wPskvtk2Ficfl0pH.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///72r4uAQGsa8KEv0DB2TpSu31lEB.jpg',
            urlvideo: '',
            Cast: [3, 4, 5, 6],
            Genres: ['série'],
        },
        {
            id: 8,
            titre: 'Hamilton',
            Overview: "Presenting the tale of American founding father Alexander Hamilton, this filmed version of the original Broadway smash hit is the story of America then, told by America now.",
            ReleasedDate: '03-07-2020',
            Favorites: false,
            Rating: 8.7,
            Runtime: 160,
            nbview: 0,
            ImgCaroussel: '',
            ImgAff: 'http://image.tmdb.org/t/p/w500///h1B7tW0t399VDjAcWJh8m87469b.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///uWVkEo9PWHu9algZsiLPi6sRU64.jpg',
            urlvideo: '',
            Cast: [7, 8, 9, 10],
            Genres: ['film'],
        },
        {
            id: 9,
            titre: 'Red Shoes and the Seven Dwarfs',
            Overview: "Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.",
            ReleasedDate: '25-07-2019',
            Favorites: false,
            Rating: 6.7,
            Runtime: 92,
            nbview: 0,
            ImgCaroussel: '',
            ImgAff: 'http://image.tmdb.org/t/p/w500///MBiKqTsouYqAACLYNDadsjhhC0.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///bga3i5jcejBekr2FCGJga1fYCh.jpg',
            urlvideo: '',
            Cast: [1, 8, 5, 10],
            Genres: ['Dessin Animé'],
>>>>>>> 0f658371c23a960ef7067489c9becaccb9a73305
        },

        {
            id: 10,
            titre: 'Red Shoes and the Seven Dwarfs',
            Overview: "Phasellus a nulla vitae augue convallis efficitur.Nam gravida viverra velit venenatis elementum.Phasellus egestas volutpa.",
            ReleasedDate: '25-07-2019',
            Favorites: false,
            Rating: 9,
            Runtime: 120,
            nbview: 0,
            ImgCaroussel: '.\..\imgfilms\ImgCarou\gravity.jpg',
            ImgAff: 'http://image.tmdb.org/t/p/w500///MBiKqTsouYqAACLYNDadsjhhC0.jpg',
            Imgband: 'http://image.tmdb.org/t/p/w500///bga3i5jcejBekr2FCGJga1fYCh.jpg',
            urlvideo: '',
            Cast: [4, 7, 3, 11],
            Genres: ['Film'],
        },

    ]

    static ListCast = [
        {
            id: 1,
            Nom: 'Harrison Ford',
            img: 'https://image.tmdb.org/t/p/w200/ewNO5cjiCa3d1qKnPhrapyz58od.jpg',
        },
        {
            id: 2,
            Nom: 'Rutger Hauer',
            img: 'https://image.tmdb.org/t/p/w200/45kp2fmVWloddrz7LF94MmT4tWf.jpg',
        },
        {
            id: 3,
            Nom: 'Sean Young',
            img: 'https://image.tmdb.org/t/p/w200/qzXxAAn5D3A2OEKejkMMV5vmVFr.jpg',
        },
        {
            id: 4,
            Nom: 'Edward James Olmos',
            img: 'https://image.tmdb.org/t/p/w200/hEzrHwFVSmistZJEUYtVXh7cwPO.jpg',
        },
        {
            id: 5,
            Nom: 'Leonardo DiCaprio',
            img: 'https://image.tmdb.org/t/p/w200/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg',
        },
        {
            id: 6,
            Nom: 'Joseph Gordon-Levitt',
            img: 'https://image.tmdb.org/t/p/w200/4U9G4YwTlIEbAymBaseltS38eH4.jpg',
        },
        {
            id: 7,
            Nom: 'Ellen Page',
            img: 'https://image.tmdb.org/t/p/w200/9klYBqJZIMNscul78QxPwzWrur9.jpg',
        },
        {
            id: 8,
            Nom: 'Tom Hardy',
            img: 'https://image.tmdb.org/t/p/w200/4CR1D9VLWZcmGgh4b6kKuY2NOel.jpg',
        },
        {
            id: 9,
            Nom: 'Will Forte',
            img: 'https://image.tmdb.org/t/p/w200/kphnirb7YggSVEhGI47kACxaIJQ.jpg',
        },
        {
            id: 10,
            Nom: 'Frank Welker',
            img: 'https://image.tmdb.org/t/p/w200/b3gImArbw13mMKJIe9leFc9YYb7.jpg',
        },
        {
            id: 11,
            Nom: 'Amanda Seyfried',
            img: 'https://image.tmdb.org/t/p/w200/kkWFJ2Ygu6ZcQgrldOnjhHg7WOk.jpg',
        },
        {
            id: 12,
            Nom: 'Mark Wahlberg',
            img: 'https://image.tmdb.org/t/p/w200/bTEFpaWd7A6AZVWOqKKBWzKEUe8.jpg',
        },
    ]
}